WhateverGen/MvcApplication1/Models/Reporte.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using WhateverGenNHibernate.EN.Whatever;

namespace MvcApplication1.Models
{
    public class Reporte
    {

        //public void ReportarEvento (int id_usuario, int id_evento, string motivo)
        //public void ReportarReto (int id_usuario, int id_reto, string motivo)

        //private WhateverGenNHibernate.EN.Whatever.UsuarioEN usuario_reporte;
        [Display(Prompt = "Usuario del reporte", Description = "Usuario del reporte", Name = "Usuario")]
        public UsuarioEN Usuario { get; set; }

        //private string motivo;
        [Display(Prompt = "Motivo del reporte", Description = "Motivo del reporte", Name = "Motivo")]
        [Required(ErrorMessage = "Debe indicar un motivo para el reporte")]
        [StringLength(maximumLength: 200, ErrorMessage = "El motivo no puede tener más de 200 caracteres")]
        public string Motivo { get; set; }

        //private int iD;
        [ScaffoldColumn(false)]
        public int id { get; set; }

        //private WhateverGenNHibernate.EN.Whatever.UsuarioEN usuario;
        [ScaffoldColumn(false)]
        public int idUsuario { get; set; }
               
        //private WhateverGenNHibernate.EN.Whatever.RetoEN reto;
        [ScaffoldColumn(false)]
        public int idReto { get; set; }

        //private WhateverGenNHibernate.EN.Whatever.EventoEN evento;
        [ScaffoldColumn(false)]
        public int idEvento { get; set; }

        //id gymkana
        [ScaffoldColumn(false)]
        public int idGymkana { get; set; }

    }
}

WhateverGen/MvcApplication1/Controllers/ReporteController.cs
using MvcApplication1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WhateverGenNHibernate.CAD.Whatever;
using WhateverGenNHibernate.CP.Whatever;
using WhateverGenNHibernate.EN.Whatever;

namespace MvcApplication1.Controllers
{
    [Authorize(Roles = "usuario")]

    public class ReporteController : BasicController
    {
        //
        // GET: /Reporte/
        public ActionResult Index()
        {
            SessionInitialize();
            ReporteCAD cad = new ReporteCAD(session);
            var aux = cad.GetAll(0,0);

            SessionClose();

            return View(aux);
        }

        public ActionResult IndexEvento(int id)
        {
            SessionInitialize();
            ReporteCAD cad = new ReporteCAD(session);
            var aux = cad.FiltrarReportesPorEvento(id);

            SessionClose();

            return View(aux);
        }

        public ActionResult IndexGymkana(int id)
        {
            SessionInitialize();
            ReporteCAD cad = new ReporteCAD(session);
            var aux = cad.FiltrarReportesPorGymkana(id);

            SessionClose();

            return View(aux);
        }

        public ActionResult IndexReto(int id)
        {
            SessionInitialize();
            ReporteCAD cad = new ReporteCAD(session);
            var aux = cad.FiltrarReportesPorReto(id);

            SessionClose();

            return View(aux);
        }

        //
        // GET: /Reporte/Details/5

        public ActionResult Details(int id)
        {
            Reporte rep = null;
            SessionInitialize();
            ReporteEN pasEN = new ReporteCAD(session).ReadOIDDefault(id);
            rep = new AssemblerReporte().ConvertENToModelUI(pasEN);
            if (!Roles.IsUserInRole("admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            SessionClose();
            return View(rep);
        }

        //
        // GET: /Reporte/CreateGymkana

        public ActionResult CreateGymkana(int id)
        {
            SessionInitialize();

            Reporte rep = new Reporte();

            rep.idGymkana = id;
            
            SessionClose();
            return View(rep);
        }

        //
        // GET: /Reporte/CreateEvento
        public ActionResult CreateEvento(int id)
        {
            SessionInitialize();

            Reporte rep = new Reporte();

            rep.idEvento = id;

            SessionClose();
            return View(rep);
        }

        //
        // GET: /Reporte/CreateReto
        public ActionResult CreateReto(int id)
        {
            SessionInitialize();

            Reporte rep = new Reporte();

            rep.idReto = id;

            SessionClose();
            return View(rep);
        }

        //
        // POST: /Reporte/CreateEvento

        [HttpPost]
        public ActionResult CreateEvento(Reporte rep)
        {
            try
            {
                UsuarioCAD usucad = new UsuarioCAD();
                UsuarioEN usuen = usucad.FiltrarUsuarioPorNombre(User.Identity.Name);
                ReporteCP repcp = new ReporteCP();
                EventoCAD evcad = new EventoCAD();
                EventoEN even = evcad.GetID(rep.idEvento);

                repcp.ReportarEvento(usuen.ID, even.ID, rep.Motivo);
                
                return RedirectToAction("IndexEvento", new { id = rep.idEvento });

            }
            catch
            {
                return View();
            }
        }

        //
        // POST: /Reporte/CreateGymkana

        [HttpPost]
        public ActionResult CreateGymkana(Reporte rep)
        {
            try
            {
                UsuarioCAD usucad = new UsuarioCAD();
                UsuarioEN usuen = usucad.FiltrarUsuarioPorNombre(User.Identity.Name);
                ReporteCP repcp = new ReporteCP();
                GymkanaCAD gymcad = new GymkanaCAD();
                GymkanaEN gymen = gymcad.GetID(rep.idGymkana);

                repcp.ReportarGymkana(usuen.ID, gymen.ID, rep.Motivo);

                return RedirectToAction("IndexGymkana", new { id = rep.idGymkana });

            }
            catch
            {
                return View();
            }
        }

        //
        // POST: /Reporte/CreateReto

        [HttpPost]
        public ActionResult CreateReto(Reporte rep)
        {
            try
            {
                UsuarioCAD usucad = new UsuarioCAD();
                UsuarioEN usuen = usucad.FiltrarUsuarioPorNombre(User.Identity.Name);
                ReporteCP repcp = new ReporteCP();
                RetoCAD retcad = new RetoCAD();
                RetoEN reten = retcad.GetID(rep.idReto);

                repcp.ReportarReto(usuen.ID, reten.ID, rep.Motivo);

                return RedirectToAction("IndexReto", new { id = rep.idReto });

            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Reporte/Delete/5

        public ActionResult Delete(int id)
        {
            Reporte rep = null;
            SessionInitialize();
            ReporteEN repen = new ReporteCAD(session).ReadOIDDefault(id);
            rep = new AssemblerReporte().ConvertENToModelUI(repen);
            if (!Roles.IsUserInRole("admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            SessionClose();
            return View(rep);
        }

        //
        // POST: /Reporte/Delete/5

        [HttpPost]
        public ActionResult Delete(Reporte rep)
        {
            try
            {
                ReporteCP cp = new ReporteCP();
                ReporteEN repen = new ReporteCAD().GetID(rep.id);
                cp.BorrarUnReporte(rep.id);
                if (repen.Evento != null)
                    return RedirectToAction("IndexEvento", new { id = repen.Evento.ID });
                else if (repen.Gymkana != null)
                    return RedirectToAction("IndexGymkana", new { id = repen.Gymkana.ID });
                else if (repen.Reto != null)
                    return RedirectToAction("IndexReto", new { id = repen.Reto.ID });

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WhateverGen/MvcApplication1/Controllers/RetoController.cs
using MvcApplication1.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WhateverGenNHibernate.CAD.Whatever;
using WhateverGenNHibernate.CEN.Whatever;
using WhateverGenNHibernate.CP.Whatever;
using WhateverGenNHibernate.EN.Whatever;


namespace MvcApplication1.Controllers
{
    [Authorize(Roles = "usuario")]

    public class RetoController : BasicController
    {
        //
        // GET: /Reto/

        public ActionResult Index()
        {
            SessionInitialize();
            RetoCAD cad = new RetoCAD(session);
            var aux = cad.GetAll(0, 0);
            

            return View(aux);

        }

        //
        // GET: /Reto/Details/5

        public ActionResult Details(int id)
        {
            Reto ret = null;
            SessionInitialize();
            RetoEN retEN = new RetoCAD(session).ReadOIDDefault(id);
            ret = new AssemblerReto().ConvertENToModelUI(retEN);
            SessionClose();
            return View(ret);
        }

        //
        // GET: /Reto/Create

        public ActionResult Create()
        {
            Reto ret = new Reto();
            ret.Creador = User.Identity.Name;
            return View(ret);
        }

        //
        // POST: /Reto/Create

        [HttpPost]
        public ActionResult Create(Reto ret, HttpPostedFileBase file)
        {

            string fileName = "", path = "";
            // Verify that the user selected a file
            if (file != null && file.ContentLength > 0)
            {
                // extract only the fielname
                fileName = Path.GetFileName(file.FileName);
                // store the file inside ~/App_Data/uploads folder
                path = Path.Combine(Server.MapPath("~/Images/Uploads"), fileName);
                //string pathDef = path.Replace(@"\\", @"\");
                file.SaveAs(path);
            }
        

            try
            {
                RetoCEN cen = new RetoCEN();
                UsuarioCAD cad = new UsuarioCAD();
                RetoEN reten = new RetoEN();
                reten.Descripcion = ret.Descripcion;
                fileName = "/Images/Uploads/" + fileName;
                reten.Imagen = fileName;
                reten.Precio = ret.Precio;
                reten.Tipo = ret.Tipo;
                reten.Titulo = ret.Titulo;
                reten.Usuario = cad.FiltrarUsuarioPorNombre(User.Identity.Name);
                //cen.New_(reten.Titulo, reten.Descripcion, reten.Tipo, reten.Precio, reten.Imagen, reten.Usuario.ID);
                cen.CrearReto(reten);

                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Reto/Edit/5

        public ActionResult Edit(int id)
        {
            Reto ret = null;
            SessionInitialize();
            RetoEN reten = new RetoCAD(session).ReadOIDDefault(id);
            UsuarioEN usu = reten.Usuario;
            ret = new AssemblerReto().ConvertENToModelUI(reten);
            if (User.Identity.Name != usu.Nombre && !Roles.IsUserInRole("admin"))
            {
                return RedirectToAction("Details", new { id = id });
            }
            SessionClose();
            return View(ret);
        }

        //
        // POST: /Reto/Edit/5

        [HttpPost]
        public ActionResult Edit(Reto ret, HttpPostedFileBase file)
        {
            string fileName = "", path = "";
            // Verify that the user selected a file
            if (file != null && file.ContentLength > 0)
            {
                // extract only the fielname
                fileName = Path.GetFileName(file.FileName);
                // store the file inside ~/App_Data/uploads folder
                path = Path.Combine(Server.MapPath("~/Images/Uploads"), fileName);
                //string pathDef = path.Replace(@"\\", @"\");
                file.SaveAs(path);
            }
            
            try
            {
                RetoCEN cen = new RetoCEN();
                RetoEN reten = new RetoEN();
                reten.ID = ret.id;
                reten.Descripcion = ret.Descripcion;
                reten.Imagen = ret.Imagen;
                fileName = "/Images/Uploads/" + fileName;
                if (ret.Imagen != fileName && fileName != "/Images/Uploads/")
                {
                    reten.Imagen = fileName;
                }
                else
                {
                reten.Imagen = ret.Imagen;
                }
                reten.Precio = ret.Precio;
                reten.Tipo = ret.Tipo;
                reten.Titulo = ret.Titulo;
                reten.Usuario = ret.usuario;
                
                
                cen.ModificarReto(reten);
;               return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Reto/Delete/5

        public ActionResult Delete(int id)
        {
            Reto ret = null;
            SessionInitialize();
            RetoEN reten = new RetoCAD(session).ReadOIDDefault(id);
            ret = new AssemblerReto().ConvertENToModelUI(reten);
            UsuarioEN usu = reten.Usuario;
            ret = new AssemblerReto().ConvertENToModelUI(reten);
            if (User.Identity.Name != usu.Nombre && !Roles.IsUserInRole("admin"))
            {
                return RedirectToAction("Details", new { id = id });
            }
            SessionClose();
            return View(ret);
        }

        //
        // POST: /Reto/Delete/5

        [HttpPost]
        public ActionResult Delete(Reto ret)
        {
            try
            {
                RetoCP cp = new RetoCP();
                cp.BorrarReto(ret.id);



                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Reto/List

        public ActionResult List()
        {
            SessionInitialize();
            RetoCAD cad = new RetoCAD(session);
            UsuarioCAD usucad = new UsuarioCAD(session);
            UsuarioEN usuen = usucad.FiltrarUsuarioPorNombre(User.Identity.Name);
            var aux = cad.FiltrarRetoPorUsuario(usuen.ID);
            SessionClose();

            return View(aux);

        }
    }
}

WhateverGen/MvcApplication1/Views/Reporte/CreateEvento.cshtml
@model MvcApplication1.Models.Reporte

@{
    ViewBag.Title = "Crear reporte en Evento";
}

<h2>Crear reporte en Evento</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    

        <div class="editor-label">
            @Html.LabelFor(model => model.Motivo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Motivo)
            @Html.ValidationMessageFor(model => model.Motivo)
        </div>
        <div class="editor-field">
            @Html.HiddenFor(model => model.idEvento)
            @Html.ValidationMessageFor(model => model.idEvento)
        </div>
        <p>
            <input type="submit" value="Create" class="waves-effect waves-light btn"  />
        </p>
}

<div>
    @Html.ActionLink("Volver al Evento", "Details", "Evento", new { id = Model.idEvento }, new { @class = "waves-effect waves-light white-text btn marme" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WhateverGen/MvcApplication1/Views/Reporte/CreateGymkana.cshtml
@model MvcApplication1.Models.Reporte

@{
    ViewBag.Title = "Crear reporte en Gymkana";
}

<h2>Crear reporte en Gymkana</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    

        <div class="editor-label">
            @Html.LabelFor(model => model.Motivo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Motivo)
            @Html.ValidationMessageFor(model => model.Motivo)
        </div>
        <div class="editor-field">
            @Html.HiddenFor(model => model.idGymkana)
            @Html.ValidationMessageFor(model => model.idGymkana)
        </div>
        <p>
            <input type="submit" value="Create"  class="waves-effect waves-light btn" />
        </p>
}

<div>
    @Html.ActionLink("Volver a la Gymkana", "Details", "Gymkana", new { id = Model.idGymkana }, new { @class = "waves-effect waves-light white-text btn marme" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WhateverGen/MvcApplication1/Views/Reporte/CreateReto.cshtml
@model MvcApplication1.Models.Reporte

@{
    ViewBag.Title = "Crear reporte en Reto";
}

<h2>Crear reporte en Reto</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    

        <div class="editor-label">
            @Html.LabelFor(model => model.Motivo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Motivo)
            @Html.ValidationMessageFor(model => model.Motivo)
        </div>
        <div class="editor-field">
            @Html.HiddenFor(model => model.idReto)
            @Html.ValidationMessageFor(model => model.idReto)
        </div>
        <p>
            <input type="submit" value="Crear"  class="waves-effect waves-light btn" />
        </p>
}

<div>
    @Html.ActionLink("Volver al Reto", "Details", "Reto", new { id = Model.idReto }, new { @class = "waves-effect waves-light white-text btn marme" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WhateverGen/MvcApplication1/Views/Reporte/Delete.cshtml
@model MvcApplication1.Models.Reporte

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Reporte</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Motivo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Motivo)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> 
    </p>
}

WhateverGen/MvcApplication1/Views/Reporte/Details.cshtml
@model MvcApplication1.Models.Reporte

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Reporte</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Motivo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Motivo)
    </div>
    <div class="display-label">
        Nombre Usuario
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Usuario.Nombre)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

WhateverGen/MvcApplication1/Views/Reporte/Index.cshtml
@model IEnumerable<WhateverGenNHibernate.EN.Whatever.ReporteEN>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Motivo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Motivo)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

WhateverGen/MvcApplication1/Views/Reporte/IndexEvento.cshtml
@model IEnumerable<WhateverGenNHibernate.EN.Whatever.ReporteEN>

@{
    ViewBag.Title = "Ver reportes de Evento";
}

<h2>Ver reportes de Evento</h2>


<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Motivo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Motivo)
        </td>
        
        <td>
            @Html.ActionLink("Detalles", "Details", "Reporte", new { id=item.ID }, new { @class = "waves-effect waves-light white-text btn marme" }) 
            @Html.ActionLink("Delete", "Delete", "Reporte", new { id=item.ID }, new { @class = "waves-effect waves-light white-text btn marme" }) 
            @Html.ActionLink("Volver al Evento", "Details", "Evento", new { id = item.Evento.ID }, new { @class = "waves-effect waves-light white-text btn marme" })


        </td>
    </tr>
}

</table>

WhateverGen/MvcApplication1/Views/Reporte/IndexGymkana.cshtml
@model IEnumerable<WhateverGenNHibernate.EN.Whatever.ReporteEN>

@{
    ViewBag.Title = "Ver reportes de Gymkana";
}

<h2>Ver reportes de Gymkana</h2>

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Motivo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Motivo)
        </td>
        <td>
            @Html.ActionLink("Detalles", "Details", "Reporte", new { id = item.ID }, new { @class = "waves-effect waves-light white-text btn marme" })
            @Html.ActionLink("Delete", "Delete", "Reporte", new { id = item.ID }, new { @class = "waves-effect waves-light white-text btn marme" })
            @Html.ActionLink("Volver a la Gymkana", "Details", "Gymkana", new { id = item.Gymkana.ID }, new { @class = "waves-effect waves-light white-text btn marme" })
        </td>
    </tr>
}

</table>

WhateverGen/MvcApplication1/Views/Reporte/IndexReto.cshtml
@model IEnumerable<WhateverGenNHibernate.EN.Whatever.ReporteEN>

@{
    ViewBag.Title = "ver reportes de Reto";
}

<h2>Rerportes de Reto</h2>

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Motivo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Motivo)
        </td>
        <td>
            @Html.ActionLink("Detalles", "Details", "Reporte", new { id=item.ID }, new { @class = "waves-effect waves-light white-text btn marme" }) 
            @Html.ActionLink("Delete", "Delete", "Reporte", new { id = item.ID }, new { @class = "waves-effect waves-light white-text btn marme" }) 
            @Html.ActionLink("Volver al Reto", "Details", "Reto", new { id = item.Reto.ID }, new { @class = "waves-effect waves-light white-text btn marme" })
        </td>
    </tr>
}

</table>

WhateverGen/MvcApplication1/Views/Reporte/borrarReporte.cshtml
@model WhateverGenNHibernate.EN.Whatever.ReporteEN

@{
    ViewBag.Title = "borrarReporte";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>borrarReporte</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>ReporteEN</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Motivo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Motivo)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

WhateverGen/MvcApplication1/Views/Reporte/consultarReporte.cshtml
@model WhateverGenNHibernate.EN.Whatever.ReporteEN

@{
    ViewBag.Title = "consultarReporte";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>consultarReporte</h2>

<fieldset>
    <legend>ReporteEN</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Motivo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Motivo)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WhateverGen/MvcApplication1/Views/Reporte/reportarReporte.cshtml
@model WhateverGenNHibernate.EN.Whatever.ReporteEN

@{
    ViewBag.Title = "reportarReporte";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>reportarReporte</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>ReporteEN</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Motivo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Motivo)
            @Html.ValidationMessageFor(model => model.Motivo)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}