WhateverGen/MvcApplication1/Models/Comentario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Collections.Generic;
using WhateverGenNHibernate.EN.Whatever;

namespace MvcApplication1.Models
{
    public class Comentario
    {
        /*    
        COMENTARIO EN
        private string texto;
        private string creador;
        private int iD;
        private WhateverGenNHibernate.EN.Whatever.UsuarioEN comentario_usuario;
        private WhateverGenNHibernate.EN.Whatever.EventoEN comentario_evento2;
        private WhateverGenNHibernate.EN.Whatever.RetoEN comentario_reto;
        
        public void CrearComentarioParaEvento (ComentarioEN comentario, int id_evento)
        public void CrearComentarioParaReto (ComentarioEN comentario, int id_reto) 
        
         */

        //private string creador;
        [Display(Prompt = "Creador del comentario", Description = "Creador del comentario", Name = "Creador")]
        [Required(ErrorMessage = "Debe indicar un creador para el comentario")]
        [StringLength(maximumLength: 40, ErrorMessage = "El nombre no puede tener más de 40 caracteres")]
        public string Creador { get; set; }

        //private string nombre;
        [Display(Prompt = "Texto del comentario", Description = "Texto del comentario", Name = "Texto")]
        [Required(ErrorMessage = "Debe indicar un texto para el comentario")]
        [StringLength(maximumLength: 300, ErrorMessage = "El texto no puede tener más de 300 caracteres")]
        public string Texto { get; set; }
       
        //private int iD;
        [ScaffoldColumn(false)]
        public int id { get; set; }

        [ScaffoldColumn(false)]
        public int idGymkana { get; set; }

        //private WhateverGenNHibernate.EN.Whatever.UsuarioEN usuario;
        [Required(ErrorMessage = "Debe indicar un creador para el comentario")]
        public UsuarioEN usuario;

        //private WhateverGenNHibernate.EN.Whatever.EventoEN evento;
        [ScaffoldColumn(false)]
        public int idEvento;

        //private WhateverGenNHibernate.EN.Whatever.RetoEN reto;
        [ScaffoldColumn(false)]
        public int idReto;

    }
}

WhateverGen/MvcApplication1/Controllers/ComentarioController.cs
using MvcApplication1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WhateverGenNHibernate.CAD.Whatever;
using WhateverGenNHibernate.CEN.Whatever;
using WhateverGenNHibernate.CP.Whatever;
using WhateverGenNHibernate.EN.Whatever;

namespace MvcApplication1.Controllers
{
    [Authorize(Roles = "usuario")]
    public class ComentarioController : BasicController
    {
        //
        // GET: /Comentario/

        public ActionResult ComentarioEvento(int id)
        {
            SessionInitialize();
            ComentarioCAD cad = new ComentarioCAD(session);
            var aux = cad.FiltrarComentarioPorEvento(id);

            SessionClose();

            return View(aux);
        }

        public ActionResult ComentarioGymkana(int id)
        {
            SessionInitialize();
            ComentarioCAD cad = new ComentarioCAD(session);
            var aux = cad.FiltrarComentarioPorGymkana(id);

            SessionClose();

            return View(aux);
        }

        public ActionResult ComentarioReto(int id)
        {
            SessionInitialize();
            ComentarioCAD cad = new ComentarioCAD(session);
            var aux = cad.FiltrarComentarioPorReto(id);

            SessionClose();

            return View(aux);
        }

        //
        // GET: /Comentario/CreateGymkana

        public ActionResult CreateGymkana(int id)
        {
            SessionInitialize();

            Comentario com = new Comentario();

            com.Creador = User.Identity.Name;
            com.idGymkana = id;

            SessionClose();
            return View(com);
        }

        //
        // GET: /Comentario/CreateEvento

        public ActionResult CreateEvento(int id)
        {
            SessionInitialize();

            Comentario com = new Comentario();

            com.Creador = User.Identity.Name;
            com.idEvento = id;

            SessionClose();
            return View(com);
        }

        //
        // GET: /Comentario/CreateReto

        public ActionResult CreateReto(int id)
        {
            SessionInitialize();

            Comentario com = new Comentario();

            com.Creador = User.Identity.Name;
            com.idReto = id;

            SessionClose();
            return View(com);
        }

        //
        // POST: /Comentario/CreateEvento

        [HttpPost]
        public ActionResult CreateEvento(Comentario com)
        {
            try
            {
                UsuarioCAD usucad = new UsuarioCAD();
                UsuarioEN usuen = usucad.FiltrarUsuarioPorNombre(User.Identity.Name);
                ComentarioCP comcp = new ComentarioCP();
                EventoCAD evcad = new EventoCAD();
                EventoEN even = evcad.GetID(com.id);

                comcp.CrearComentarioParaEvento(even.ID, com.Texto, usuen.ID);

                return RedirectToAction("ComentarioEvento", new { id = com.id });

            }
            catch
            {
                return View();
            }
        }

        //
        // POST: /Comentario/CreateGymkana

        [HttpPost]
        public ActionResult CreateGymkana(Comentario com)
        {
            try
            {
                UsuarioCAD usucad = new UsuarioCAD();
                UsuarioEN usuen = usucad.FiltrarUsuarioPorNombre(User.Identity.Name);
                ComentarioCP comcp = new ComentarioCP();
                GymkanaCAD gymcad = new GymkanaCAD();
                GymkanaEN gymen = gymcad.GetID(com.id);

                comcp.CrearComentarioParaGymkana(gymen.ID, com.Texto, usuen.ID);

                return RedirectToAction("ComentarioGymkana", new { id = com.id });

            }
            catch
            {
                return View();
            }
        }

        //
        // POST: /Comentario/CreateReto

        [HttpPost]
        public ActionResult CreateReto(Comentario com)
        {
            try
            {
                UsuarioCAD usucad = new UsuarioCAD();
                UsuarioEN usuen = usucad.FiltrarUsuarioPorNombre(User.Identity.Name);
                ComentarioCP comcp = new ComentarioCP();
                RetoCAD retcad = new RetoCAD();
                RetoEN reten = retcad.GetID(com.id);

                comcp.CrearComentarioParaReto(reten.ID, com.Texto, usuen.ID);

                return RedirectToAction("ComentarioReto", new { id = com.id });

            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Comentario/Delete/5

        public ActionResult Delete(int id)
        {
            Comentario com = null;
            SessionInitialize();
            ComentarioEN comen = new ComentarioCAD(session).ReadOIDDefault(id);
            com = new AssemblerComentario().ConvertENToModelUI(comen);
            UsuarioEN usu = com.usuario;
            if (User.Identity.Name != usu.Nombre && !Roles.IsUserInRole("admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            SessionClose();
            return View(com);
        }

        //
        // POST: /Comentario/DeleteEvento/5

        [HttpPost]
        public ActionResult Delete(Comentario com)
        {
           try
            {
                ComentarioCP cp = new ComentarioCP();
                ComentarioEN comen = new ComentarioCAD().GetID(com.id);
                cp.BorrarUnComentario(com.id);
                if (comen.Evento != null)
                    return RedirectToAction("ComentarioEvento", new { id = comen.Evento.ID });
                else if (comen.Gymkana != null)
                    return RedirectToAction("ComentarioGymkana", new { id = comen.Gymkana.ID });
                else 
                    return RedirectToAction("ComentarioReto", new { id = comen.Reto.ID });

            }
            catch
            {
                return View();
            }
        }
    }
}

WhateverGen/MvcApplication1/Controllers/RetoController.cs
using MvcApplication1.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WhateverGenNHibernate.CAD.Whatever;
using WhateverGenNHibernate.CEN.Whatever;
using WhateverGenNHibernate.CP.Whatever;
using WhateverGenNHibernate.EN.Whatever;


namespace MvcApplication1.Controllers
{
    [Authorize(Roles = "usuario")]

    public class RetoController : BasicController
    {
        //
        // GET: /Reto/

        public ActionResult Index()
        {
            SessionInitialize();
            RetoCAD cad = new RetoCAD(session);
            var aux = cad.GetAll(0, 0);
            

            return View(aux);

        }

        //
        // GET: /Reto/Details/5

        public ActionResult Details(int id)
        {
            Reto ret = null;
            SessionInitialize();
            RetoEN retEN = new RetoCAD(session).ReadOIDDefault(id);
            ret = new AssemblerReto().ConvertENToModelUI(retEN);
            SessionClose();
            return View(ret);
        }

        //
        // GET: /Reto/Create

        public ActionResult Create()
        {
            Reto ret = new Reto();
            ret.Creador = User.Identity.Name;
            return View(ret);
        }

        //
        // POST: /Reto/Create

        [HttpPost]
        public ActionResult Create(Reto ret, HttpPostedFileBase file)
        {

            string fileName = "", path = "";
            // Verify that the user selected a file
            if (file != null && file.ContentLength > 0)
            {
                // extract only the fielname
                fileName = Path.GetFileName(file.FileName);
                // store the file inside ~/App_Data/uploads folder
                path = Path.Combine(Server.MapPath("~/Images/Uploads"), fileName);
                //string pathDef = path.Replace(@"\\", @"\");
                file.SaveAs(path);
            }
        

            try
            {
                RetoCEN cen = new RetoCEN();
                UsuarioCAD cad = new UsuarioCAD();
                RetoEN reten = new RetoEN();
                reten.Descripcion = ret.Descripcion;
                fileName = "/Images/Uploads/" + fileName;
                reten.Imagen = fileName;
                reten.Precio = ret.Precio;
                reten.Tipo = ret.Tipo;
                reten.Titulo = ret.Titulo;
                reten.Usuario = cad.FiltrarUsuarioPorNombre(User.Identity.Name);
                //cen.New_(reten.Titulo, reten.Descripcion, reten.Tipo, reten.Precio, reten.Imagen, reten.Usuario.ID);
                cen.CrearReto(reten);

                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Reto/Edit/5

        public ActionResult Edit(int id)
        {
            Reto ret = null;
            SessionInitialize();
            RetoEN reten = new RetoCAD(session).ReadOIDDefault(id);
            UsuarioEN usu = reten.Usuario;
            ret = new AssemblerReto().ConvertENToModelUI(reten);
            if (User.Identity.Name != usu.Nombre && !Roles.IsUserInRole("admin"))
            {
                return RedirectToAction("Details", new { id = id });
            }
            SessionClose();
            return View(ret);
        }

        //
        // POST: /Reto/Edit/5

        [HttpPost]
        public ActionResult Edit(Reto ret, HttpPostedFileBase file)
        {
            string fileName = "", path = "";
            // Verify that the user selected a file
            if (file != null && file.ContentLength > 0)
            {
                // extract only the fielname
                fileName = Path.GetFileName(file.FileName);
                // store the file inside ~/App_Data/uploads folder
                path = Path.Combine(Server.MapPath("~/Images/Uploads"), fileName);
                //string pathDef = path.Replace(@"\\", @"\");
                file.SaveAs(path);
            }
            
            try
            {
                RetoCEN cen = new RetoCEN();
                RetoEN reten = new RetoEN();
                reten.ID = ret.id;
                reten.Descripcion = ret.Descripcion;
                reten.Imagen = ret.Imagen;
                fileName = "/Images/Uploads/" + fileName;
                if (ret.Imagen != fileName && fileName != "/Images/Uploads/")
                {
                    reten.Imagen = fileName;
                }
                else
                {
                reten.Imagen = ret.Imagen;
                }
                reten.Precio = ret.Precio;
                reten.Tipo = ret.Tipo;
                reten.Titulo = ret.Titulo;
                reten.Usuario = ret.usuario;
                
                
                cen.ModificarReto(reten);
;               return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Reto/Delete/5

        public ActionResult Delete(int id)
        {
            Reto ret = null;
            SessionInitialize();
            RetoEN reten = new RetoCAD(session).ReadOIDDefault(id);
            ret = new AssemblerReto().ConvertENToModelUI(reten);
            UsuarioEN usu = reten.Usuario;
            ret = new AssemblerReto().ConvertENToModelUI(reten);
            if (User.Identity.Name != usu.Nombre && !Roles.IsUserInRole("admin"))
            {
                return RedirectToAction("Details", new { id = id });
            }
            SessionClose();
            return View(ret);
        }

        //
        // POST: /Reto/Delete/5

        [HttpPost]
        public ActionResult Delete(Reto ret)
        {
            try
            {
                RetoCP cp = new RetoCP();
                cp.BorrarReto(ret.id);



                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Reto/List

        public ActionResult List()
        {
            SessionInitialize();
            RetoCAD cad = new RetoCAD(session);
            UsuarioCAD usucad = new UsuarioCAD(session);
            UsuarioEN usuen = usucad.FiltrarUsuarioPorNombre(User.Identity.Name);
            var aux = cad.FiltrarRetoPorUsuario(usuen.ID);
            SessionClose();

            return View(aux);

        }
    }
}

WhateverGen/MvcApplication1/Views/Comentario/ComentarioEvento.cshtml
@model IEnumerable<WhateverGenNHibernate.EN.Whatever.ComentarioEN>

@{
    ViewBag.Title = "ComentarioEvento";
}

<h2>Comentarios en Eventos</h2>

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Texto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Creador)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Texto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Creador)
        </td>
        <td>
            @Html.ActionLink("Borrar", "Delete", "Comentario", new { id=item.ID }, new { @class = "waves-effect waves-light white-text btn marme" }) 
            @Html.ActionLink("Volver al Evento", "Details","Evento", new { id = item.Evento.ID }, new { @class = "waves-effect waves-light white-text btn marme" })
            
        </td>
    </tr>
}

</table>

WhateverGen/MvcApplication1/Views/Comentario/ComentarioGymkana.cshtml
@model IEnumerable<WhateverGenNHibernate.EN.Whatever.ComentarioEN>

@{
    ViewBag.Title = "ComentarioGymkana";
}

<h2>Comentarios en Gymkanas</h2>

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Texto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Creador)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Texto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Creador)
        </td>
        <td>
            @Html.ActionLink("Delete", "Delete", "Comentario", new { id = item.ID }, new { @class = "waves-effect waves-light white-text btn marme" }) |
            @Html.ActionLink("Volver a la Gymkana", "Details", "Gymkana", new { id = item.Gymkana.ID }, new { @class = "waves-effect waves-light white-text btn marme" })
        </td>
    </tr>
}

</table>

WhateverGen/MvcApplication1/Views/Comentario/ComentarioReto.cshtml
@model IEnumerable<WhateverGenNHibernate.EN.Whatever.ComentarioEN>

@{
    ViewBag.Title = "ComentarioReto";
}

<h2>Comentarios en Retos</h2>


<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Texto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Creador)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Texto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Creador)
        </td>
        <td>
            @Html.ActionLink("Borrar", "Delete", "Comentario",  new { id = item.ID }, new { @class = "waves-effect waves-light white-text btn marme" }) 
            @Html.ActionLink("Volver al Reto", "Details", "Reto", new { id = item.Reto.ID }, new { @class = "waves-effect waves-light white-text btn marme" })
        </td>
    </tr>
}

</table>

WhateverGen/MvcApplication1/Views/Comentario/CreateEvento.cshtml
@model MvcApplication1.Models.Comentario

@{
    ViewBag.Title = "Crear comentario en Evento";
}

<h2>Crear comentario en Evento</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Comentario</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Texto)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Texto)
            @Html.ValidationMessageFor(model => model.Texto)
        </div>
        <div class="editor-field">
            @Html.HiddenFor(model => model.idEvento)
            @Html.ValidationMessageFor(model => model.idEvento)
        </div>

        <p>
            <input type="submit" value="Create" class="waves-effect waves-light btn" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Volver al Evento", "Details", "Evento", new { id = Model.idEvento }, new { @class = "waves-effect waves-light white-text btn marme" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WhateverGen/MvcApplication1/Views/Comentario/CreateGymkana.cshtml
@model MvcApplication1.Models.Comentario

@{
    ViewBag.Title = "Crear comentario en Gymkana";
}

<h2>Crear comentario en Gymkana</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Comentario</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Texto)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Texto)
            @Html.ValidationMessageFor(model => model.Texto)
        </div>
        <div class="editor-field">
            @Html.HiddenFor(model => model.idGymkana)
            @Html.ValidationMessageFor(model => model.idGymkana)
        </div>

        <p>
            <input type="submit" value="Crear"  class="waves-effect waves-light btn"/>
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Volver a la Gymkana", "Details", "Gymkana", new { id = Model.idGymkana }, new { @class = "waves-effect waves-light white-text btn marme" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WhateverGen/MvcApplication1/Views/Comentario/CreateReto.cshtml
@model MvcApplication1.Models.Comentario

@{
    ViewBag.Title = "CreateReto";
}

<h2>Comentar en Reto</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    

        <div class="editor-label">
            @Html.LabelFor(model => model.Texto)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Texto)
            @Html.ValidationMessageFor(model => model.Texto)
        </div>
        <div class="editor-field">
            @Html.HiddenFor(model => model.idReto)
            @Html.ValidationMessageFor(model => model.idReto)
        </div>

        <p>
            <input type="submit" value="Crear" class="waves-effect waves-light btn" /> 
        </p>
}

<div>
    @Html.ActionLink("Volver al Reto", "Details", "Reto", new { id = Model.idReto }, new { @class = "waves-effect waves-light white-text btn marme" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WhateverGen/MvcApplication1/Views/Comentario/Delete.cshtml
@model MvcApplication1.Models.Comentario

@{
    ViewBag.Title = "Delete";
}

<h2>Borrar</h2>

<h3>¿Deseas borrar el evento @Html.DisplayFor(model => model.Texto)?</h3>
<fieldset>
    <legend>Comentario</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Creador)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Creador)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Texto)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Texto)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Borrar" class="waves-effect waves-light white-text btn" /> 
    </p>
}

WhateverGen/MvcApplication1/Views/Comentario/Index.cshtml
@model IEnumerable<WhateverGenNHibernate.EN.Whatever.ComentarioEN>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Texto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Creador)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Texto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Creador)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

WhateverGen/MvcApplication1/Views/Comentario/borrarComentario.cshtml
@model WhateverGenNHibernate.EN.Whatever.ComentarioEN

@{
    ViewBag.Title = "borrarComentario";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>borrarComentario</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>ComentarioEN</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Texto)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Texto)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Creador)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Creador)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

WhateverGen/MvcApplication1/Views/Comentario/crearComentario.cshtml
@model WhateverGenNHibernate.EN.Whatever.ComentarioEN

@{
    ViewBag.Title = "crearComentario";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>crearComentario</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>ComentarioEN</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Texto)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Texto)
            @Html.ValidationMessageFor(model => model.Texto)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Creador)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Creador)
            @Html.ValidationMessageFor(model => model.Creador)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WhateverGen/MvcApplication1/Views/Comentario/modificarComentario.cshtml
@model WhateverGenNHibernate.EN.Whatever.ComentarioEN

@{
    ViewBag.Title = "modificarComentario";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>modificarComentario</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>ComentarioEN</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Texto)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Texto)
            @Html.ValidationMessageFor(model => model.Texto)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Creador)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Creador)
            @Html.ValidationMessageFor(model => model.Creador)
        </div>

        @Html.HiddenFor(model => model.ID)

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}