WhateverGen/MvcApplication1/Models/Evento.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Collections.Generic;
using WhateverGenNHibernate.EN.Whatever;

namespace MvcApplication1.Models
{
    public class Evento
    {
        /*
        EVENTO EN   
        private string titulo;
        private string descripcion;
        private Nullable<DateTime> fecha;
        private int precio;
        private UsuarioEN usuario;
        private IList<PuntuacionEN> puntuacion;
        private IList<MapaEN> mapa;
        private IList<ComentarioEN> comentario;
        private int iD;
        private IList<ReporteEN> reporte;
        private double latitud;
        private double longitud;
        private int zoom;
        */
        //public void CrearEvento (WhateverGenNHibernate.EN.Whatever.EventoEN evento, double lat, double long_, int zoom)


        //Titulo
        [Display(Prompt = "Titulo del evento", Description = "Titulo del evento", Name = "Titulo")]
        [Required(ErrorMessage = "Debe indicar un titulo para el evento")]
        [StringLength(maximumLength: 100, ErrorMessage = "El titulo no puede tener más de 100 caracteres")]
        public string Titulo { get; set; }

        //Descripcion
        [Display(Prompt = "Descripción del evento", Description = "Descripción del evento", Name = "Descripcion")]
        [Required(ErrorMessage = "Debe indicar una descripción para el evento")]
        [StringLength(maximumLength: 200, ErrorMessage = "La descripción no puede tener más de 200 caracteres")]
        public string Descripcion { get; set; }

        //Fecha
        [Display(Prompt = "Fecha del evento", Description = "Fecha del evento", Name = "Fecha")]
        [DataType(DataType.Date, ErrorMessage = "La fecha debe ser valida")]
        [Required(ErrorMessage = "Debe indicar una fecha para el evento")]
        public Nullable<DateTime> Fecha { get; set; }

        //Precio
        [Display(Prompt = "Precio del evento", Description = "Precio del evento", Name = "Precio")]
        [Required(ErrorMessage = "Debe indicar un precio para el evento")]
        [DataType(DataType.Currency, ErrorMessage = "El precio debe ser un valor numérico")]
        [Range(minimum: 0.0, maximum: 10000.0, ErrorMessage = "El precio debe ser mayor que cero y menor de 10000")]
        public double Precio { get; set; }

        //Creador
        [Display(Prompt = "Creador", Description = "Nombre del creador del evento", Name = "Creador")]
        [Required(ErrorMessage = "Debe indicar el nombre del creador del evento")]
        public string Creador { get; set; }

        //Latitud
        [Display(Prompt = "Latitud del evento", Description = "Latitud del evento", Name = "Latitud")]
        [Required(ErrorMessage = "Debe indicar una latitud para el evento")]
        //[DataType(DataType.Custom, ErrorMessage = "La latitud debe ser numerica")]
        [Range(-90.00000000, 90.00000000, ErrorMessage = "El valor de {0} tiene que ser correcto e ir entre {1} y {2}")]
        public string Latitud { get; set; }

        //Longitud
        [Display(Prompt = "Longitud del evento", Description = "Longitud del evento", Name = "Longitud")]
        [Required(ErrorMessage = "Debe indicar una longitud para el evento")]
        //[DataType(DataType.Currency, ErrorMessage = "La longitud debe ser numerica")]
        [Range(-180.00000000, 180.00000000, ErrorMessage = "El valor de {0} tiene que ser correcto e ir entre {1} y {2}")]
        public string Longitud { get; set; }

        //Zoom
        [Display(Prompt = "Zoom para el mapa", Description = "Zoom para el mapa", Name = "Zoom")]
        [Required(ErrorMessage = "Debe indicar un zoom para el mapa")]
        [Range(minimum: 2, maximum: 20, ErrorMessage = "El zoom debe ser mayor que 2 y menor de 20")]
        public int Zoom { get; set; }

        //private IList<PuntuacionEN> puntuacion;
        [Display(Prompt = "Puntuacion", Description = "Puntuacion del evento", Name = "Puntuacion")]
        public IList<Puntuacion> Puntuaciones { get; set; }
        
        //private IList<MapaEN> mapa;
        [Display(Prompt = "Mapa", Description = "Mapa del evento", Name = "Mapa")]
        public Mapa Mapa{ get; set; }

        //private IList<ComentarioEN> comentario;
        [Display(Prompt = "Comentarios", Description = "Comentarios del evento", Name = "Comentario")]
        public IList<Comentario> Comentarios { get; set; }

        //private IList<ReporteEN> reporte;
        [Display(Prompt = "Reportes", Description = "Reportes del evento", Name = "Reportes")]
        public IList<Reporte> Reportes { get; set; }



        //private int iD;
        [ScaffoldColumn(false)]
        public int id { get; set; }

        //private UsuarioEN usuario;
        [ScaffoldColumn(false)]
        public UsuarioEN usuario { get; set; }



    }
}

WhateverGen/MvcApplication1/Controllers/EventoController.cs
using MvcApplication1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WhateverGenNHibernate.CAD.Whatever;
using WhateverGenNHibernate.CEN.Whatever;
using WhateverGenNHibernate.CP.Whatever;
using WhateverGenNHibernate.EN.Whatever;

namespace MvcApplication1.Controllers
{
    [Authorize(Roles = "usuario")]
    public class EventoController : BasicController
    {
        //
        // GET: /Evento/

        public ActionResult Index()
        {
            SessionInitialize();
            EventoCAD cad = new EventoCAD(session);
            var aux = cad.GetAll(0, 0);

            SessionClose();

            return View(aux);
        }

        //
        // GET: /Evento/Details/5

        public ActionResult Details(int id)
        {
            Evento ev = null;
            SessionInitialize();
            EventoEN evEN = new EventoCAD(session).ReadOIDDefault(id);
            ev = new AssemblerEvento().ConvertENToModelUI(evEN);
            SessionClose();
            return View(ev);
        }

        //
        // GET: /Evento/Create

        public ActionResult Create()
        {
            SessionInitialize();

            Evento ev = new Evento();
            ev.Creador = User.Identity.Name;

            SessionClose();
            return View(ev);
        }

        //
        // POST: /Evento/Create

        [HttpPost]
        public ActionResult Create(Evento ev)
        {            
            try
            {
                UsuarioCAD cad = new UsuarioCAD();
                EventoCP cp = new EventoCP();
                EventoEN even = new EventoEN();
                even.Descripcion = ev.Descripcion;
                even.Fecha = ev.Fecha;
                even.Precio = ev.Precio;
                even.Titulo = ev.Titulo;
                even.Usuario = cad.FiltrarUsuarioPorNombre(User.Identity.Name);
                cp.CrearEvento(even, ev.Latitud,ev.Longitud,ev.Zoom);

                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Evento/Edit/5

        public ActionResult Edit(int id)
        {
            Evento ev = null;
            SessionInitialize();
            EventoEN even = new EventoCAD(session).ReadOIDDefault(id);
            ev = new AssemblerEvento().ConvertENToModelUI(even);
            UsuarioEN usu = ev.usuario;
            if (User.Identity.Name != usu.Nombre && !Roles.IsUserInRole("admin"))
            {
                return RedirectToAction("Details", new { id = id });
            }
            SessionClose();
            return View(ev);

        }

        //
        // POST: /Evento/Edit/5

        [HttpPost]
        public ActionResult Edit(Evento ev)
        {
            try
            {
                EventoCEN cen = new EventoCEN();

                cen.Modify(ev.id,ev.Titulo,ev.Descripcion,ev.Fecha,ev.Precio);
                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Evento/Delete/5

        public ActionResult Delete(int id)
        {
            Evento ev = null;
            SessionInitialize();
            EventoEN even = new EventoCAD(session).ReadOIDDefault(id);
            ev = new AssemblerEvento().ConvertENToModelUI(even);
            UsuarioEN usu = ev.usuario;
            if (User.Identity.Name != usu.Nombre && !Roles.IsUserInRole("admin"))
            {
                return RedirectToAction("Details", new { id = id });
            }
            SessionClose();
            return View(ev);
        }

        //
        // POST: /Evento/Delete/5

        [HttpPost]
        public ActionResult Delete(Evento ev)
        {
            try
            {

                EventoCP cp = new EventoCP();
                cp.BorrarEvento(ev.id);


                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Evento/List

        public ActionResult List()
        {
            SessionInitialize();
            EventoCAD cad = new EventoCAD(session);
            UsuarioCAD usucad = new UsuarioCAD(session);
            UsuarioEN usuen = usucad.FiltrarUsuarioPorNombre(User.Identity.Name);
            var aux = cad.FiltrarEventoPorUsuario(usuen.ID);

            SessionClose();

            return View(aux);
        }
    }
}

WhateverGen/MvcApplication1/Views/Evento/Create.cshtml
@model MvcApplication1.Models.Evento

@{
    ViewBag.Title = "Nuevo Evento";
}

<h2>Nuevo Evento</h2>

@using (Html.BeginForm("Create", "Evento", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Evento</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Titulo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Titulo)
            @Html.ValidationMessageFor(model => model.Titulo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Descripcion)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Descripcion)
            @Html.ValidationMessageFor(model => model.Descripcion)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Fecha)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Fecha)
            @Html.ValidationMessageFor(model => model.Fecha)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Precio)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Precio)
            @Html.ValidationMessageFor(model => model.Precio)
        </div>
        <!-- 
        <div class="editor-label">
            @Html.LabelFor(model => model.Latitud)
        </div>
        -->
        <div class="editor-field">
            @Html.HiddenFor(model => model.Latitud)
            @Html.ValidationMessageFor(model => model.Latitud)
        </div>
        <!--
        <div class="editor-label">
            @Html.LabelFor(model => model.Longitud)
        </div>
        -->
        <div class="editor-field">
            @Html.HiddenFor(model => model.Longitud)
            @Html.ValidationMessageFor(model => model.Longitud)
        </div>
        <!--
        <div class="editor-label">
            @Html.LabelFor(model => model.Zoom)
        </div>
        -->
        <div class="editor-field">
            @Html.HiddenFor(model => model.Zoom)
        </div>
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}
<h3>Mapa</h3>
<div id="map" style="height: 600px;"></div>

<div>
    @Html.ActionLink("Volver a Eventos", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/mapacreate")
}
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAQw5mBOiJP88UP8TbwysOHmKg0NFRS2Rg"></script>

WhateverGen/MvcApplication1/Views/Evento/Delete.cshtml
@model MvcApplication1.Models.Evento

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Evento</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Titulo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Titulo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Descripcion)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Descripcion)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Fecha)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Fecha)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Precio)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Precio)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Creador)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Creador)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Latitud)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Latitud)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Longitud)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Longitud)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Zoom)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Zoom)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Volver a Eventos", "List")
    </p>
}

WhateverGen/MvcApplication1/Views/Evento/Details.cshtml
@model MvcApplication1.Models.Evento

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles @Html.DisplayFor(model => model.Titulo)</h2>

<fieldset>
    <legend>Evento</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Titulo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Titulo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Descripcion)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Descripcion)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Fecha)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Fecha)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Precio)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Precio)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Creador)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Creador)
    </div>
    
</fieldset>

<h3>Mapa</h3>
<div id="map" style="height: 600px; "></div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Comentar", "CreateEvento", "Comentario", new { id = Model.id }, "null") |
    @Html.ActionLink("Ver Comentarios", "ComentarioEvento", "Comentario", new { id = Model.id }, "null") |
    @Html.ActionLink("Puntuar", "CreateEvento", "Puntuacion", new { id = Model.id }, "null") |
    @Html.ActionLink("Reportar", "CreateEvento", "Reporte", new { id = Model.id }, "null") |
    @Html.ActionLink("Ver reportes", "IndexEvento", "Reporte", new { id = Model.id }, "null") |
    @Html.ActionLink("Ver puntuaciones", "PuntuacionEvento", "Puntuacion", new { id = Model.id }, "null") |
    @Html.ActionLink("Volver a Eventos", "List") 
</p>


<script>
    //var titulo = document.getElementById("lat").innerHTML;
    //var latitud = parseFloat(document.getElementById("lat").innerHTML);
    //var longitud = parseFloat(document.getElementById("lon").innerHTML);

    var titulo = "@Html.DisplayFor(model => model.Titulo)";
    var descripcion = "@Html.DisplayFor(model => model.Descripcion)";
    var latitud = parseFloat("@Html.DisplayFor(model => model.Latitud)");
    var longitud = parseFloat("@Html.DisplayFor(model => model.Longitud)");
</script>

@section Scripts {
    @Scripts.Render("~/bundles/mapadetail")
}
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAQw5mBOiJP88UP8TbwysOHmKg0NFRS2Rg"></script>

WhateverGen/MvcApplication1/Views/Evento/Edit.cshtml
@model MvcApplication1.Models.Evento

@{
    ViewBag.Title = "Editar";
}

<h2>Editar @Html.DisplayFor(model => model.Titulo)</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Evento</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Titulo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Titulo)
            @Html.ValidationMessageFor(model => model.Titulo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Descripcion)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Descripcion)
            @Html.ValidationMessageFor(model => model.Descripcion)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Fecha)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Fecha)
            @Html.ValidationMessageFor(model => model.Fecha)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Precio)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Precio)
            @Html.ValidationMessageFor(model => model.Precio)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Latitud)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Latitud)
            @Html.ValidationMessageFor(model => model.Latitud)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Longitud)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Longitud)
            @Html.ValidationMessageFor(model => model.Longitud)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Zoom)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Zoom)
            @Html.ValidationMessageFor(model => model.Zoom)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Volver a Eventos", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WhateverGen/MvcApplication1/Views/Evento/Index.cshtml
@model IEnumerable<WhateverGenNHibernate.EN.Whatever.EventoEN>

@{
    ViewBag.Title = "Eventos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eventos</h2>

<p>
    @Html.ActionLink("Nuevo Evento", "Create")
</p>
<p>
    @Html.ActionLink("Mis Eventos", "List")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Precio)
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Titulo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Precio) €
        </td>
       
        <td>
            @Html.ActionLink("Editar", "Edit", new { id = item.ID }) |
            @Html.ActionLink("Detalles", "Details", new { id = item.ID }) |
            @Html.ActionLink("Borrar", "Delete", new { id = item.ID }) |
            @Html.ActionLink("Ver Comentarios", "ComentarioEvento", "Comentario", new { id = item.ID }, "null") |
            @Html.ActionLink("Ver reportes", "IndexEvento", "Reporte", new { id = item.ID }, "null") 

        </td>
        
    </tr>
}

</table>

WhateverGen/MvcApplication1/Views/Evento/List.cshtml
@model IEnumerable<WhateverGenNHibernate.EN.Whatever.EventoEN>

@{
    ViewBag.Title = "Mis Eventos";
}

<h2>Mis Eventos</h2>

<p>
    @Html.ActionLink("Nuevo Evento", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Precio)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Titulo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Precio) €
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Detalles", "Details", new { id=item.ID }) |
            @Html.ActionLink("Borrar", "Delete", new { id=item.ID }) |            
            @Html.ActionLink("Ver Comentarios", "ComentarioEvento", "Comentario", new { id = item.ID }, "null") |
            @Html.ActionLink("Ver reportes", "IndexEvento", "Reporte", new { id = item.ID }, "null")

            

        </td>
    </tr>
}

</table>
<div>
    @Html.ActionLink("Volver a Eventos", "Index")
</div>